optiopay/klar

main.go
There is no reasonable default clair address until somebody provides a public service.
=> Fail when clair address is not set

clair/clair.go, clair/clair_test.go
@hashmap   I have finished the enhancement. PTAL, thanks.
Fix #6
=> Enhancement: get vulnerabilities by image's non-empty top layer

docker/docker.go
Since earlier this year Google Container Registry (GCR) stores images manifests in manifest schema 2 format[1]. Two of the changes to the schema are that name and tag has been removed. If the client does not indicate support for manifest schema version 2, GCR will assume that the client does not support it and convert the schema to v1. In order to generate valid (schema version 1) JSON GCR sets the values of name and tag to "unused". 
This causes problems for Klar since the response of the manifest request is decoded into the Image struct, effectively setting the name and tag values to "unused".
This PR adds request headers that indicate support for manifest schema version 2. 
See my bug report to GCR for more details.
[1] https://github.com/docker/distribution/blob/master/docs/spec/manife …
=> Request manifest schema version 2

README.md, docker/docker.go, main.go
Allows Klar to access registries with bad SSL certificates (e.g. if you're testing out a private repo setup locally)
=> Add optional support for insecure registries

README.md, docker/docker.go, main.go
This allows Klar to pull from insecure HTTP-only registries, like one shipped with Openshift.
=> Allow insecure/http registry

clair/clair.go, docker/docker.go, main.go
It's a good practice to send errors to stderr only. That way, json output won't be messed up when something goes wrong, like a layer that failed to be push()ed.
Also, merged and extended #31
=> Print errors to stderr only

docker/docker.go, docker/docker_test.go
Enables addressing images by sha256 digest as an alternative to tags, e.g. postgres@sha256:f6a2b81d981ace74aeafb2ed2982d52984d82958bfe836b82cbe4bf1ba440999.
=> Allow sha256 digest image addressing

docker/docker.go
This change fix pulling of public images (#42). Currently, Klar always expects
DOCKER_USER to be specified which is not required in this particular
case.
This behavior is hard to test in unit tests, the integration test is not a part of the project yet. Also we don't have integration tests running as part of PR process, I do it on my machine and use my env file which contains DOCKER_USER. Now I run it twice with different env files. I'll create a separate issue for test & build improvement.
=> Fix scaning of public images

docker/docker.go, docker/docker_test.go
This fix removes hostname resolution from image name parsing function.
It decreases time of tests execution from 15 secs to 0.02 on my machine.
The drawback is that we can't use short hostname (except localhost) as a
registry hostname. However docker client itself doesn't support such
hostnames, so it's a safe assumption for Klar.
https://github.com/moby/moby/blob/master/vendor/github.com/docker/distribution/reference/normalize.go#L64
=> Speed up image name parsing

README.md
docker images built on linux will not work otherwise, because they are dynamically linked. The scratch image does not provide a libc.
See https://blog.codeship.com/building-minimal-docker-containers-for-go-applications/ for more info
=> Updated Readme to make static build possible

clair/clair.go, docker/docker.go, main.go, utils/http.go
* Remove manifest list from accepted types 
* Registry v2 returns layers in the reverse order, support both orders
* Add tracing support
=> Full support of registry v2 and Clair v2

main.go
When JSON_OUTPUT var is true, its nice to only output json for a successful scan so I can be parsed or piped to jq
=> Remove non JSON logging when JSON variable is true

docker/docker.go
* Can't pull fsLayers with public GCR image #83
=> Fixes for release 2.0.2

README.md, docker/docker.go, klar.go
This allows for specifying a token and still pulling from the unauthenticated dockerhub, the same behavior the DOCKER_USER and DOCKER_PASSWORD allows.
=> Add support for existing registry tokens per optiopay/klar#18

README.md, clair/api.go, clair/api_test.go, clair/clair.go, clair/clair_test.go, docker/docker.go, klar.go, main.go
This pull request adds support to configure clair (API v1) and docker timeouts using environment variables. Fixes #88
=> Add support to configure docker/clair timeouts

docker/docker.go
If token is specified (for a private registry, for example), but not correct (i.e. the image is for the public docker registry), but we can obtain a proper token (like if the image is in a public docker registry), we should ignore the passed in token and get the proper token.
=> Fix edgecase if token is specified and not needed

main.go, main_test.go, whitelist-example.yaml
* e.g. "fluent/fluent-bit" instead of "debian"
* fixes #104 
If you want to avoid a breaking change to the whitelist semantics, we could also introduce a third section (something like `specificImages`), but I am not sure if this is necessary.
=> Use whitelist for specific image instead of base.

Dockerfile, klar.go, main.go
Adds the option not to count unfixed vulnerabilities when calculating klar's exit code.
Fixes [#109](https://github.com/optiopay/klar/issues/109).
=> Add support for ignoring unfixed vulnerabilities

README.md, main.go
Also updated the README to reflect this change. This should *not* break any automated tools that run klar and check for non-zero exit status. It will break tools that specifically check for an exit status of `1`.
=> Modify exit status, to distinguish between runtime errors and vulnerabilities being present.

main.go
Resolves #132 
The `store` object needs to be populated by `groupBySeverity` before calling `jsonFormat`
=> Ensure vuln-store is populated before calling jsonFormat

clair/clair_test.go, vendor/github.com/coreos/clair/api/v3/clairpb/convert.go
The database.Ancestry protobuf has changed format and now contains a database.AncestryLayer instead of a database.Layer.
=> Fix build that has broken from a protobuf update

docker/docker.go, main.go
* Fix typo in main.go
* Sum up 2 if clauses in one in docker.go
* Add error message if Docker Registry sends unsupported Content-Type
(this occurs for example in #137)
=> Small fixes and added error message for unsupported content-type

docker/docker.go
While leveraging the klar repo, we noticed the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb868c9]
goroutine 3890993 [running]:
github.com/optiopay/klar/docker.(*Image).requestToken(0xc00551bec0, 0xc01d6fcfc0, 0x0, 0x0, 0x0, 0x0)
/tmp/build/ae5c2d4a/go/pkg/mod/github.com/optiopay/klar@v2.4.0+incompatible/docker/docker.go:295 +0x6e9
github.com/optiopay/klar/docker.(*Image).Pull(0xc00551bec0, 0x0, 0x0)
/tmp/build/ae5c2d4a/go/pkg/mod/github.com/optiopay/klar@v2.4.0+incompatible/docker/docker.go:222 +0x1e1
go.aporeto.io/claire/internal/scanner.(*clairScanner).cacheImage(0xc0003ac540, 0xc009ec3e60, 0xf, 0xc04f6d3e40, 0xc0154aaa90)
```
The response is not checked if it is `nil` prior …
=> Fixed: Try to drain response body only if response exists
